import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const base = process.env.API_URL || 'http://127.0.0.1:4300/api';
const headers = { 'x-access-key': process.env.DEV_ACCESS_KEY || 'local-viskopic-development-key' };
async function call(path, method = 'GET', body, expected = 200) {
  const response = await fetch(base + path, { method, headers: { ...headers, 'content-type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  const value = await response.json();
  assert.equal(response.status, expected, JSON.stringify(value));
  return value;
}
async function upload(student, course, expected = 201) {
  const form = new FormData();
  form.append('file', new Blob(['Synthetic cross-course writing.']), 'cross-course.txt');
  const response = await fetch(`${base}/submissions?studentId=${student}&courseId=${course}`, { method: 'POST', headers, body: form });
  const result = await response.json();
  assert.equal(response.status, expected, JSON.stringify(result));
  return result;
}
const suffix = randomUUID();
const a = await call('/courses', 'POST', { name: 'Profile course A ' + suffix }, 201);
const b = await call('/courses', 'POST', { name: 'Profile course B ' + suffix }, 201);
const c = await call('/courses', 'POST', { name: 'Not enrolled ' + suffix }, 201);
const student = await call('/students', 'POST', { reference: 'PROFILE-' + suffix, name: 'Synthetic cross-course student' }, 201);
await call(`/courses/${a.id}/enrolments`, 'POST', { studentId: student.id }, 201);
await call(`/courses/${b.id}/enrolments`, 'POST', { studentId: student.id }, 201);
await call(`/courses/${b.id}/enrolments`, 'POST', { studentId: student.id }, 409);
await call(`/courses/${c.id}/students`, 'POST', { reference: student.reference }, 409);
await call(`/courses/${randomUUID()}/enrolments`, 'POST', { studentId: student.id }, 404);
await upload(student.id, c.id, 404);
await upload(student.id, '', 400);
const first = await upload(student.id, a.id);
const second = await upload(student.id, b.id);
const all = await call(`/submissions?studentId=${student.id}`);
assert.equal(all.length, 2);
assert.deepEqual(new Set(all.map(d => d.course_id)), new Set([a.id,b.id]));
assert.equal((await call(`/submissions?studentId=${student.id}&courseId=${a.id}`)).length, 1);
const profile = (await call('/students')).find(s => s.id === student.id);
assert.equal(profile.document_count, 2);
assert.equal(profile.course_count, 2);
assert.equal((await call(`/courses/${a.id}/students`))[0].document_count, 1);
await call(`/courses/${a.id}/enrolments/${student.id}`, 'PATCH', { archived: true });
await upload(student.id, a.id, 409);
await upload(student.id, b.id);
assert.equal((await call(`/submissions?studentId=${student.id}`)).length, 3);
await call(`/courses/${a.id}/enrolments/${student.id}`, 'DELETE', undefined, 409);
await call(`/courses/${a.id}/enrolments/${student.id}`, 'PATCH', { archived: false });
await call(`/submissions/${first.id}`, 'PATCH', { studentId: student.id, courseId: c.id }, 404);
await call(`/submissions/${first.id}`, 'PATCH', { studentId: student.id, courseId: b.id });
assert.equal((await call(`/submissions/${first.id}`)).course_id, b.id);
assert.equal((await call(`/submissions/${second.id}`)).student_id, student.id);
await call(`/courses/${a.id}/enrolments/${student.id}`, 'DELETE');
assert.equal((await call(`/students/${student.id}/courses`)).length, 1);
await call(`/courses/${a.id}`, 'DELETE');
await call(`/courses/${c.id}`, 'DELETE');
await call(`/students/${student.id}`, 'DELETE', undefined, 409);
await call(`/students/${student.id}`, 'PATCH', { archived: true });
await upload(student.id, b.id, 409);
await call(`/students/${student.id}`, 'PATCH', { archived: false });
console.log('PASS: shared profile, global reference uniqueness, cross-course history and counts, enrolment lifecycle, required course, moves and archive restrictions.');
